apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ebms.out.payload
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  pool: nav-prod
  acl:
    - team: team-emottak
      application: ebms-send-in
      access: write   # read, write, readwrite

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ebms.out.payload
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  pool: nav-prod
  acl:
    - team: team-emottak
      application: ebms-async
      access: read   # read, write, readwrite
