apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ebms.out.payload
  namespace: team-emottak
  labels:
    team: team-emottak
spec:
  pool: nav-prod
  acl:
    - team: team-emottak
      application: send-in-send-out
      access: readwrite   # read, write, readwrite