apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "ebms-send-in"
  namespace: "team-emottak"
  labels:
    "team": "team-emottak"
spec:
  azure:
    application:
      enabled: true
  webproxy: true
  image: {{image}}
  liveness:
    path: "/internal/health/liveness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  prometheus:
    enabled: true
    path: /prometheus
  readiness:
    path: "/internal/health/readiness"
    port: 8080
    initialDelay: 30
    timeout: 10
    failureThreshold: 10
  replicas:
    scalingStrategy:
      cpu:
        thresholdPercentage: 50
    min: 1
    max: 4
  resources:
    limits:
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"
  ingresses:
    - "https://ebms-send-in.intern.dev.nav.no"
  vault:
    enabled: true
    paths:
        - kvPath: /serviceuser/data/dev/srvtokt
          mountPath: /secret/serviceuser
  kafka:
    pool: nav-dev
  accessPolicy:
    inbound:
      rules:
        - application: ebms-provider
        - application: ebms-async
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
  envFrom:
    - secret: emottak-mq-creds
  env:
    - name: FRIKORT_URL
      value: https://wasapp-q1.adeo.no/nav-frikort/tjenestereksterne
    - name: PASIENTLISTE_URL
      value: https://wasapp-q1.adeo.no/nav-emottak-practitioner-web/remoting/httpreqhandler-practitioner
    - name: EMOTTAK_LOGGING_LEVEL
      value: DEBUG
    - name: SERVICEUSER_SECRET_PATH
      value: /secret/serviceuser
    - name: FRIKORT_REST_PERCENT
      value: "100"
    - name: TREKKOPPL_MQ_HOST
      value: "mqls04.preprod.local"
    - name: TREKKOPPL_MQ_PORT
      value: "1413"
    - name: TREKKOPPL_MQ_QMGR
      value: "MQLS04"
    - name: TREKKOPPL_MQ_CHANNEL
      value: "Q1_EMOTTAK_ASYNCH"
    - name: TREKKOPPL_MQ_QUEUE
      value: "QA.Q1_231.OB04_INNRAPP_TREKK"
