import com.github.jengelman.gradle.plugins.shadow.transformers.AppendingTransformer
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.gradle.kotlin.dsl.testLibs

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm")
    kotlin("plugin.serialization")
    application
    id("io.ktor.plugin")
    id("org.jlleitschuh.gradle.ktlint") version "11.6.1"
    id("org.openapi.generator") version "7.6.0"
}

openApiGenerate {
    generatorName.set("kotlin")
    inputSpec.set(file("$projectDir/src/main/resources/frikort/frikortsporringer.yaml").toURI().toString())
    outputDir.set(layout.buildDirectory.dir("generated/openapi").get().asFile.path)
    packageName.set("no.helsedir.frikort.frikorttjenester")
    modelPackage.set("no.helsedir.frikort.frikorttjenester.model")
    configOptions.set(
        mapOf(
            "dateLibrary" to "kotlinx-datetime",
            "serializationLibrary" to "kotlinx_serialization"
        )
    )
    globalProperties.set(
        mapOf(
            "models" to "",
            "modelTests" to "false",
            "modelDocs" to "false",
            "apis" to "false",
            "invokers" to "false"
        )
    )
}

sourceSets {
    main {
        java {
            srcDir(layout.buildDirectory.dir("generated/openapi/src/main/kotlin").get().asFile.path)
        }
    }
}

tasks {
    shadowJar {
        mergeServiceFiles()
        transform(AppendingTransformer::class.java) {
            this.resource = "META-INF/cxf/bus-extensions.txt"
        }
        archiveFileName.set("app.jar")
    }
    register<Wrapper>("wrapper") {
        gradleVersion = "8.14"
    }
    test {
        useJUnitPlatform()
        testLogging.showStandardStreams = true
        testLogging {
            events("passed", "skipped", "failed")
            showExceptions = true
            showCauses = true
            showStackTraces = true
            exceptionFormat = TestExceptionFormat.FULL
        }
    }
    runKtlintCheckOverMainSourceSet {
        mustRunAfter("openApiGenerate")
    }
    runKtlintFormatOverMainSourceSet {
        mustRunAfter("openApiGenerate")
    }
    compileKotlin {
        dependsOn("openApiGenerate")
    }
    ktlintFormat {
        this.enabled = true
    }
    ktlintCheck {
        dependsOn("ktlintFormat")
    }
    build {
        dependsOn("ktlintCheck")
    }
}

ktlint {
    filter {
        exclude { it.file.path.contains("/generated/") }
        exclude { it.file.path.contains("\\generated\\") }
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().all {
    compilerOptions {
        freeCompilerArgs = listOf("-opt-in=kotlin.uuid.ExperimentalUuidApi,com.sksamuel.hoplite.ExperimentalHoplite")
    }
}

dependencies {
    implementation(libs.emottak.utils)
    implementation(libs.saaj.impl)
    implementation(libs.hoplite.core)
    implementation(libs.hoplite.hocon)
    implementation(libs.arrow.core)
    implementation(libs.arrow.functions)
    implementation(libs.arrow.fx.coroutines)
    implementation(libs.arrow.resilience)
    implementation(libs.arrow.suspendapp)
    implementation(libs.arrow.suspendapp.ktor)
    implementation(libs.bundles.cxf)
    implementation(libs.bundles.logging)
    implementation(libs.bundles.prometheus)
    implementation(libs.ebxml.protokoll)
    implementation(libs.emottak.payload.xsd)
    implementation(libs.jaxb.runtime)
    implementation(libs.ktor.client.auth)
    implementation(libs.ktor.client.cio)
    implementation(libs.ktor.client.cio.jvm)
    implementation(libs.ktor.client.content.negotiation)
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.ktor.server.auth.jvm)
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.core.jvm)
    implementation(libs.ktor.server.call.logging.jvm)
    implementation(libs.ktor.server.netty)
    implementation(libs.labai.jsr305x.annotations)
    implementation(libs.token.validation.ktor.v3)
    implementation(libs.jakarta.jms.api)
    implementation(libs.ibm.mq.allclient)
    implementation(libs.kotlinx.coroutines.slf4j)
    implementation(libs.stacktrace.decoroutinator.jvm)
    implementation(libs.jaxb.api)
    implementation(libs.javax.activation)
    implementation(libs.kafka.clients)
    implementation(libs.kotlin.kafka)
    runtimeOnly(libs.jna)
    testImplementation(libs.apache.santuario)
    testImplementation(testLibs.junit.jupiter.api)
    testImplementation(testLibs.ktor.server.test.host)
    testImplementation(testLibs.mock.oauth2.server)
    testImplementation(testLibs.mockk.dsl.jvm)
    testImplementation(testLibs.mockk.jvm)
    testRuntimeOnly(testLibs.junit.jupiter.engine)
    testRuntimeOnly(testLibs.junit.platform.launcher)
    testImplementation(testLibs.testcontainers.kafka)
}

application {
    mainClass.set("no.nav.emottak.AppKt")
}
