server {
  port = 8080
  preWait = "5s"
}

kafka {
  groupId = "ebms-send-in"
}

ebmsInPayloadReceiver {
  active = true
  topic = "team-emottak.ebms.in.payload"
}

ebmsOutPayloadProducer {
  active = true
  topic = "team-emottak.ebms.out.payload"
}

ebmsOutFellesformatReceiver {
  active = true
  topic = "team-emottak.ebms.utsending.fellesformat"
}

frikorttjenester {
  hostname = "${FRIKORT_URL_REST:-http://frikorttjenester.teamfrikort.svc.nais.local}"
  scope = "api://"${clusterName}".teamfrikort.frikorttjenester/.default"
  harBorgerFrikortEndpoint = ${frikorttjenester.hostname}"/api/ekstern/frikortsporringer/harborgerfrikort"
  harBorgerEgenandelFritakEndpoint = ${frikorttjenester.hostname}"/api/ekstern/frikortsporringer/harborgeregenandelfritak"
  pingEndpoint = ${frikorttjenester.hostname}"/api/ekstern/frikortsporringer/ping"
}

mqConfig1 {
  hostname = "${MQ_HOST:-}"
  port = "${MQ_PORT:-1413}"
  queueManager = "${MQ_QMGR:-}"
  channel = "${MQ_CHANNEL:-}"
}

trekkopplysningmq {
  mqConfig = ${mqConfig1}
  queue = "${TREKKOPPL_MQ_QUEUE:-}"
}

syfomq {
  mqConfig = ${mqConfig1}
  queue = "${SYFO_MQ_QUEUE:-}"
}

palemq {
  mqConfig = ${mqConfig1}
  queue = "${PALE_MQ_QUEUE:-}"
}

oppgjorMq {
  mqConfig = ${mqConfig1}
  queue = "${OPPGJOR_MQ_QUEUE:-}"
}

ereseptM18Mq {
  mqConfig = ${mqConfig1}
  queue = "${ERESEPT_M18_MQ_QUEUE:-}"
}

ereseptApprecMq {
  mqConfig = ${mqConfig1}
  queue = "${ERESEPT_APPREC_MQ_QUEUE:-}"
}

eiaMq {
  mqConfig = ${mqConfig1}
  queue = "${EIA_MQ_QUEUE:-}"
}

dialogMq {
  mqConfig = ${mqConfig1}
  queue = "${DIALOG_MQ_QUEUE:-}"
}

azureAuth {
  port = 3344
  azureAd = "AZURE_AD"
  azureHttpProxy = "${HTTP_PROXY:-}"
  azureAdAuth = "${AZURE_APP_TENANT_ID:-"${azureAuth.azureAd}"}"
  azureGrantType = "client_credentials"
  azureWellKnownUrl = "${AZURE_APP_WELL_KNOWN_URL:-http://localhost:"${azureAuth.port}"/"${azureAuth.azureAd}"/.well-known/openid-configuration}"
  azureTokenEndpoint = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:-http://localhost}"
  azureAppClientId = "${AZURE_APP_CLIENT_ID:-test-aud}"
  azureAppClientSecret = "${AZURE_APP_CLIENT_SECRET:-test-secret}"
}

eventLogging {
  eventLoggingProducerActive = "true"
}

clusterName = "${NAIS_CLUSTER_NAME:-local}"
