# Kilde: https://github.com/navikt/frikort-tjenester/blob/main/src/main/resources/openapi/Frikortsporringer.yaml

openapi: 3.1.0
info:
  title: Frikortspørringer
  description: Frikortspørringer
  version: 1.0.0
servers:
  - url: 'https://<frikorttjenester baseurl>/api/ekstern/frikortsporringer'
    description: 'Endepunktet for frikortspørringene'
paths:
  /harborgerfrikort:
    post:
      description: HarBorgerFrikort
      summary: HarBorgerFrikort
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FrikortsporringRequest'
      responses:
        '200':
          description: borger har/har ikke frikort
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FrikortsporringResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error
  /harborgeregenandelfritak:
    post:
      description: HarBorgerEgenandelfritak
      summary: HarBorgerEgenandelfritak
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FrikortsporringRequest'
      responses:
        '200':
          description: borger har/har ikke egenandelfritak
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FrikortsporringResponse'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error
  /ping:
    get:
      description: Ping
      summary: Ping
      responses:
        '200':
          description: vellykket ping
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

components:
  schemas:
    FrikortsporringRequest:
      type: object
      required:
        - eiFellesformat
      properties:
        eiFellesformat:
          $ref: '#/components/schemas/EIFellesformat'
    EIFellesformat:
      type: object
      required:
        - mottakenhetBlokk
        - msgHead
      properties:
        msgHead:
          $ref: '#/components/schemas/MsgHead'
        mottakenhetBlokk:
          $ref: '#/components/schemas/MottakenhetBlokk'
    MsgHead:
      type: object
      required:
        - msgInfo
      properties:
        msgInfo:
          $ref: '#/components/schemas/MsgInfo'
        documents:
          type: array
          minItems: 1
          maxItems: 1
          items:
            $ref: '#/components/schemas/Document'
    MottakenhetBlokk:
      type: object
      properties:
        ebAction:
          type: string
        ebService:
          type: string
          enum:
            - HarBorgerEgenandelFritak
            - HarBorgerFrikort
            - HarBorgerFrikortMengde
        ebRole:
          type: string
        ebXMLSamtaleId:
          type: string
        ediLoggId:
          type: string
        mottaksId:
          type: string
        partnerReferanse:
          type: string
    MsgInfo:
      type: object
      required:
        - type
        - migVersion
        - genDate
        - msgId
        - sender
        - receiver
      properties:
        type:
          $ref: '#/components/schemas/CS'
        migVersion:
          type: string
        ack:
          $ref: '#/components/schemas/CS'
        conversationRef:
          $ref: '#/components/schemas/ConversationRef'
        genDate:
          type: string
          format: date-time
        msgId:
          type: string
        sender:
          $ref: '#/components/schemas/Sender'
        receiver:
          $ref: '#/components/schemas/Receiver'
    ConversationRef:
      type: object
      required:
        - refToParent
        - refToConversation
      properties:
        refToParent:
          type: string
        refToConversation:
          type: string
    CS:
      type: object
      properties:
        v:
          type: string
        dn:
          type: string
    Sender:
      type: object
      required:
        - organization
      properties:
        organization:
          $ref: '#/components/schemas/Organization'
        comMethod:
          $ref: '#/components/schemas/CS'
    Receiver:
      type: object
      required:
        - organization
      properties:
        organization:
          $ref: '#/components/schemas/Organization'
        comMethod:
          $ref: '#/components/schemas/CS'
    Organization:
      type: object
      properties:
        organizationName:
          type: string
        ident:
          type: array
          items:
            $ref: '#/components/schemas/Ident'
        healthcareProfessional:
          $ref: '#/components/schemas/HealthcareProfessional'
    Ident:
      type: object
      required:
        - id
        - typeId
      properties:
        id:
          type: string
        typeId:
          $ref: '#/components/schemas/CV'
    HealthcareProfessional:
      type: object
      properties:
        familyName:
          type: string
        givenName:
          type: string
        ident:
          type: array
          items:
            $ref: '#/components/schemas/Ident'
    CV:
      type: object
      properties:
        v:
          type: string
        dn:
          type: string
        s:
          type: string
    Document:
      type: object
      required:
        - refDoc
      properties:
        documentConnection:
          $ref: '#/components/schemas/CS'
        refDoc:
          $ref: '#/components/schemas/RefDoc'
    RefDoc:
      type: object
      required:
        - msgType
        - content
      properties:
        msgType:
          $ref: '#/components/schemas/CS'
        content:
          $ref: '#/components/schemas/Content'
        mimeType:
          type: string
    Content:
      type: object
      properties:
        egenandelForesporsel:
          $ref: '#/components/schemas/EgenandelForesporsel'
        egenandelForesporselV2:
          $ref: '#/components/schemas/EgenandelForesporselV2'
        egenandelSvar:
          $ref: '#/components/schemas/EgenandelSvar'
        egenandelSvarV2:
          $ref: '#/components/schemas/EgenandelSvarV2'
        egenandelMengdeForesporsel:
          $ref: '#/components/schemas/EgenandelMengdeForesporsel'
        egenandelMengdeForesporselV2:
          $ref: '#/components/schemas/EgenandelMengdeForesporselV2'
        egenandelMengdeSvar:
          $ref: '#/components/schemas/EgenandelMengdeSvar'
        egenandelMengdeSvarV2:
          $ref: '#/components/schemas/EgenandelMengdeSvarV2'
    EgenandelForesporsel:
      type: object
      properties:
        harBorgerFrikort:
          $ref: '#/components/schemas/HarBorgerFrikortParamType'
        harBorgerEgenandelfritak:
          $ref: '#/components/schemas/HarBorgerEgenandelfritakParamType'
    EgenandelForesporselV2:
      type: object
      properties:
        harBorgerFrikort:
          $ref: '#/components/schemas/HarBorgerFrikortParamTypeV2'
        harBorgerEgenandelfritak:
          $ref: '#/components/schemas/HarBorgerEgenandelfritakParamType'
    EgenandelMengdeForesporsel:
      properties:
        harBorgerFrikort:
          type: array
          items:
            $ref: '#/components/schemas/HarBorgerFrikortMengdeParamType'
    EgenandelMengdeForesporselV2:
      properties:
        harBorgerFrikort:
          type: array
          items:
            $ref: '#/components/schemas/HarBorgerFrikortMengdeParamTypeV2'
    HarBorgerFrikortParamType:
      type: object
      required:
        - borgerFnr
        - dato
      properties:
        borgerFnr:
          type: string
        dato:
          type: string
          format: date
    HarBorgerFrikortParamTypeV2:
      type: object
      required:
        - borgerFnr
        - dato
        - tjenestetypeKode
      properties:
        borgerFnr:
          type: string
        dato:
          type: string
          format: date
        tjenestetypeKode:
          type: string
          $ref: '#/components/schemas/TjenestetypeKode'
    HarBorgerEgenandelfritakParamType:
      type: object
      required:
        - borgerFnr
        - dato
      properties:
        borgerFnr:
          type: string
        dato:
          type: string
          format: date
    EgenandelSvar:
      type: object
      required:
        - status
        - svarMelding
      properties:
        status:
          $ref: '#/components/schemas/CS'
        svarMelding:
          type: string
    EgenandelSvarV2:
      type: object
      required:
        - status
        - svarMelding
      properties:
        status:
          $ref: '#/components/schemas/CS'
        svarMelding:
          type: string
    EgenandelMengdeSvar:
      type: object
      required:
        - harBorgerFrikortSvar
      properties:
        harBorgerFrikortSvar:
          type: array
          items:
            $ref: '#/components/schemas/HarBorgerFrikortSvar'
    EgenandelMengdeSvarV2:
      type: object
      required:
        - harBorgerFrikortSvar
      properties:
        harBorgerFrikortSvar:
          type: array
          items:
            $ref: '#/components/schemas/HarBorgerFrikortSvarV2'
    FrikortsporringResponse:
      type: object
      required:
        - eiFellesformat
      properties:
        eiFellesformat:
          $ref: '#/components/schemas/EIFellesformat'
    HarBorgerFrikortMengdeParamType:
      type: object
      required:
        - borgerFnr
        - dato
      properties:
        borgerFnr:
          type: string
        dato:
          type: string
          format: date
    HarBorgerFrikortMengdeParamTypeV2:
      type: object
      required:
        - borgerFnr
        - dato
        - tjenestetypeKode
      properties:
        borgerFnr:
          type: string
        dato:
          type: string
          format: date
        tjenestetypeKode:
          $ref: '#/components/schemas/TjenestetypeKode'
    HarBorgerFrikortSvar:
      type: object
      required:
        - borgerFnr
        - dato
        - status
        - svarMelding
      properties:
        borgerFnr:
          type: string
        dato:
          type: string
          format: date
        status:
          $ref: '#/components/schemas/CS'
        svarMelding:
          type: string
    HarBorgerFrikortSvarV2:
      type: object
      required:
        - borgerFnr
        - dato
        - status
        - svarMelding
        - tjenestetypeKode
      properties:
        borgerFnr:
          type: string
        dato:
          type: string
          format: date
        tjenestetypeKode:
          $ref: '#/components/schemas/TjenestetypeKode'
        status:
          $ref: '#/components/schemas/CS'
        svarMelding:
          type: string
    TjenestetypeKode:
      type: string
      enum: [A, S, B, LE, PO, HS, LR, PR, PS, TB, RH, FT, BR]
