name: Deploy kafka topics to dev
on:
  push:
    branches:
      - 'main'
    paths:
      - '.nais/kafka/kafka-dev.yaml'
      - '.github/workflows/kafka-dev.yaml'
env:
  TOPIC_FILE: .nais/kafka/kafka-dev.yaml

jobs:
  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy topics to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESOURCE: ${{ env.TOPIC_FILE }}
